- name: Configurar servidor EC2 con Docker y desplegar app Flask
  hosts: servidores
  become: true

  tasks:
    - name: Actualizar paquetes del sistema
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker.io
        state: present

    - name: Iniciar Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Crear carpeta de la app
      file:
        path: /home/ubuntu/flask-app
        state: directory
        mode: '0755'

    - name: Copiar archivos de la app al servidor
      copy:
        src: app/
        dest: /home/ubuntu/flask-app
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Construir imagen Docker de la app
      command: docker build -t flask-app /home/ubuntu/flask-app

    - name: Ejecutar contenedor de la app
      command: docker run -d -p 80:5000 --name flaskapp flask-app
      ignore_errors: true  # evita fallar si ya existe

